// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/studio-devhub/proofapi",
        "contact": {
            "name": "Studio DevHub",
            "url": "https://github.com/studio-devhub/proofapi/issues"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/studio-devhub/proofapi/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cache": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes all cached grammar check results from Redis. Does not affect the languages cache.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Clear grammar check cache",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.ClearCacheResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/check": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Submits text to LanguageTool for analysis. Results are cached in Redis for 5 minutes.\\n\\n**Maximum suggestions:** set ` + "`" + `level=picky` + "`" + ` and add ` + "`" + `enabledCategories=STYLE,PUNCTUATION,TYPOGRAPHY,GRAMMAR,MISC,CASING` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grammar"
                ],
                "summary": "Check text for grammar and spelling errors",
                "parameters": [
                    {
                        "description": "Text to check",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_languagetool.CheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_languagetool.CheckResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input or text too short/long",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "LanguageTool unavailable",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dictionary": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes all words from the client's personal dictionary.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dictionary"
                ],
                "summary": "Clear dictionary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client identifier",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.DictionaryClearResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Storage error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dictionary/words": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns all words the client has added to their personal dictionary.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dictionary"
                ],
                "summary": "List dictionary words",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client identifier",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.DictionaryListResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Storage error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Adds a word to the client's personal dictionary. Future grammar checks will ignore this word.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dictionary"
                ],
                "summary": "Add word to dictionary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client identifier",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Word to add",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/docs.DictionaryAddRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/docs.DictionaryWord"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Storage error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dictionary/words/{word}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Removes a word from the client's personal dictionary. Idempotent — no error if word does not exist.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dictionary"
                ],
                "summary": "Remove word from dictionary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client identifier",
                        "name": "X-Client-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Word to remove",
                        "name": "word",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.DictionaryRemoveResponse"
                        }
                    },
                    "400": {
                        "description": "Missing word",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Missing or invalid API key",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Storage error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the status of all services: API, LanguageTool, Redis, and WebSocket hub.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/docs.HealthResponse"
                        }
                    }
                }
            }
        },
        "/languages": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns all languages supported by the LanguageTool engine. Results are cached for 1 hour.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grammar"
                ],
                "summary": "List supported languages",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/docs.LanguageItem"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "docs.CacheStats": {
            "type": "object",
            "properties": {
                "hits": {
                    "type": "integer",
                    "example": 120
                },
                "keys": {
                    "type": "integer",
                    "example": 15
                },
                "memoryUsed": {
                    "type": "string",
                    "example": "1.19M"
                },
                "misses": {
                    "type": "integer",
                    "example": 30
                }
            }
        },
        "docs.ClearCacheResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "docs.DictionaryAddRequest": {
            "type": "object",
            "properties": {
                "language": {
                    "type": "string",
                    "example": "en-US"
                },
                "word": {
                    "type": "string",
                    "example": "Tulvo"
                }
            }
        },
        "docs.DictionaryClearResponse": {
            "type": "object",
            "properties": {
                "cleared": {
                    "type": "boolean",
                    "example": true
                },
                "clientId": {
                    "type": "string",
                    "example": "dev-client-1"
                }
            }
        },
        "docs.DictionaryListResponse": {
            "type": "object",
            "properties": {
                "clientId": {
                    "type": "string",
                    "example": "dev-client-1"
                },
                "count": {
                    "type": "integer",
                    "example": 2
                },
                "words": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docs.DictionaryWord"
                    }
                }
            }
        },
        "docs.DictionaryRemoveResponse": {
            "type": "object",
            "properties": {
                "removed": {
                    "type": "string",
                    "example": "Tulvo"
                }
            }
        },
        "docs.DictionaryWord": {
            "type": "object",
            "properties": {
                "addedAt": {
                    "type": "string",
                    "example": "2026-05-20T10:00:00Z"
                },
                "language": {
                    "type": "string",
                    "example": "en-US"
                },
                "word": {
                    "type": "string",
                    "example": "Tulvo"
                }
            }
        },
        "docs.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "unauthorized"
                }
            }
        },
        "docs.HealthResponse": {
            "type": "object",
            "properties": {
                "api": {
                    "type": "string",
                    "example": "ok"
                },
                "cacheStats": {
                    "$ref": "#/definitions/docs.CacheStats"
                },
                "languagetool": {
                    "type": "string",
                    "example": "ok"
                },
                "redis": {
                    "type": "string",
                    "example": "ok"
                },
                "websocket": {
                    "$ref": "#/definitions/docs.WebSocketStats"
                }
            }
        },
        "docs.LanguageItem": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "en-US"
                },
                "longCode": {
                    "type": "string",
                    "example": "en-US"
                },
                "name": {
                    "type": "string",
                    "example": "English (US)"
                }
            }
        },
        "docs.WebSocketStats": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "integer",
                    "example": 3
                },
                "total": {
                    "type": "integer",
                    "example": 47
                }
            }
        },
        "internal_languagetool.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_languagetool.CheckRequest": {
            "type": "object",
            "properties": {
                "clientId": {
                    "description": "Optional user identifier — used to filter matches against the user's custom dictionary",
                    "type": "string"
                },
                "disabledCategories": {
                    "description": "Comma-separated category IDs to suppress",
                    "type": "string"
                },
                "disabledRules": {
                    "description": "Comma-separated rule IDs to suppress",
                    "type": "string"
                },
                "enabledCategories": {
                    "description": "Comma-separated category IDs to enable (e.g. \"STYLE,PUNCTUATION\")",
                    "type": "string"
                },
                "enabledOnly": {
                    "description": "When true, only the rules/categories in EnabledRules/EnabledCategories run",
                    "type": "boolean"
                },
                "enabledRules": {
                    "description": "Comma-separated rule IDs to enable on top of the active profile",
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "level": {
                    "description": "\"default\" | \"picky\" — picky enables extra style/punctuation rules",
                    "type": "string"
                },
                "motherTongue": {
                    "description": "BCP 47 code of the user's native language — enables false-friends detection (e.g. \"de-DE\" for a German speaker writing English)",
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "internal_languagetool.CheckResponse": {
            "type": "object",
            "properties": {
                "cacheExpiresIn": {
                    "type": "integer"
                },
                "cached": {
                    "type": "boolean"
                },
                "checkedAt": {
                    "type": "string"
                },
                "language": {
                    "$ref": "#/definitions/internal_languagetool.Language"
                },
                "matches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_languagetool.Match"
                    }
                }
            }
        },
        "internal_languagetool.Context": {
            "type": "object",
            "properties": {
                "length": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "internal_languagetool.Language": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_languagetool.Match": {
            "type": "object",
            "properties": {
                "context": {
                    "$ref": "#/definitions/internal_languagetool.Context"
                },
                "length": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "offset": {
                    "type": "integer"
                },
                "replacements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_languagetool.Replacement"
                    }
                },
                "rule": {
                    "$ref": "#/definitions/internal_languagetool.Rule"
                }
            }
        },
        "internal_languagetool.Replacement": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "internal_languagetool.Rule": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/internal_languagetool.Category"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "issueType": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API key required for all endpoints except /v1/health",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4003",
	BasePath:         "/v1",
	Schemes:          []string{"http", "https"},
	Title:            "ProofAPI",
	Description:      "Production-ready grammar and spell-checking API powered by LanguageTool, Redis, and Go.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
